### ISSUE TITLE
Compatibility with Eloquent's getDirty() or convenience method

### ISSUE THREAD

**Issue by czim** [dimsav/laravel-translatable#120]
getDirty() does not take into account changes to translations. Perhaps there's a good reason for this, but it would be helpful if there would be a convenience method to get all 'dirty' attributes including translated ones (per locale).

**Comment by dimsav** [comment]
Good point. Can you send a PR with some tests?

**Comment by dimsav** [comment]
I tried this but I stuck with the parameter of the function `isDirty($attributes)`. I'm not sure how the code should work when this is set. 

Things get weird because `$attributes` usually refers to real attributes of the main model. Hacking this to also lookout for attributes of translations is something that causes confusion IMO.
