### ISSUE TITLE
Locale Information in seperate table

### ISSUE THREAD

**Issue by bihlmaierh** [dimsav/laravel-translatable#138]
Hello!

I want to have the locale field in another table, because I have a seperated table with countries and language codes. 

So I don't  want have the same data 2 times (lang code)

Can I add a "locale_id" with foreign key and your plugin can handle this ?

Greetings!

**Comment by dimsav** [comment]
That should work. Just update the config with "local_id" [here](https://github.com/dimsav/laravel-translatable/blob/master/src/config/translatable.php#L60) and use ids instead.

Also you have to make sure this [array](https://github.com/dimsav/laravel-translatable/blob/master/src/config/translatable.php#L13) is always properly filled, so you need 1 extra mysql call for each request.

Things will get tricky however because you will have to reference locales with numbers, like this:

```php
echo $greece->translate(1)->name; // Greece
```

If you have a database with locales, you probably know that already :)

**Comment by daverdalas** [comment]
@heikobihlmaier If you are still looking for a solution for your problem, you can check my fork of this plugin: https://github.com/daverdalas/laravel-translatable
