### ISSUE TITLE
orderBy() and with() eager loading

### ISSUE THREAD

**Issue by InToSSH** [dimsav/laravel-translatable#204]
Hello,
I am trying to get to work orderBy() and eager loading together.
It works for me using your example, but currently my query looks like this
```
Item::whereIn('category_id', $categories_to_show)->with('defVariant')->paginate(16);
```
When I tried to order it, i was using this:
```
Item::join('item_translations as t', 't.item_id', '=', 'items.id')
            ->where('locale', \App::getLocale())
            ->whereIn('category_id', $categories_to_show)
            ->groupBy('items.id')
            ->orderBy('t.title')
            ->with('translations')
            ->with('defVariant')
            ->paginate(16);
```
Problam is that now the `defVariant` (which is a relationship in `Item`) is null.
I tried different places where is specified `->with('defVariant')`but can't find a solution.
Can you please help me?

**Comment by dimsav** [comment]
Hello mate, this is a question unrelated to the package. I would love to be able to answer to your question but my time is limited. 

If somebody else wants to give it a further look that's fine by me. Otherwise I suggest you give a try to the laravel slack channel or to the forums. 

Tip: convert your eloquent code to real mysql and see if this sql represents what you want to do.
