### ISSUE TITLE
Touch parent?

### ISSUE THREAD

**Issue by BojanKogoj** [dimsav/laravel-translatable#205]
I've noticed that my parent (let's say Post) isn't getting updated_at changed if I only change translations. For now I've used touch on the parent, but is there a way for PostTranslation to tell Post to update updated_at? Not quite sure how to use it with this example: https://laravel.com/docs/5.1/eloquent-relationships#touching-parent-timestamps

**Comment by BojanKogoj** [comment]
Nevermind, it works if you add this in PostTranslation
```
protected $touches = ['post'];

	public function post()
	{
		return $this->belongsTo('App\Post');
	}
```

**Comment by arturmamedov** [comment]
Think it must be the default behaviour or not?

**Comment by Gummibeer** [comment]
The translation model isn't part of this package - and the solution @BojanKogoj provided is the right one to do it.
I don't want to bring any kind of logic that could handle it into this package because it's not the default behaviour and not everyone needs it.

The parent/translated model isn't updated so it's not default/right to touch it. For sure it could be that you need/want this - so it's easy for you to do it.
