### ISSUE TITLE
Translations are not saved when using Baum\Node

### ISSUE THREAD

**Issue by freekmurze** [dimsav/laravel-translatable#25]
Hi,

in my project I need to create a model that uses both a nested tree structured and translations. To translate the model I use your package. The nested set structure is provided by https://github.com/etrepat/baum. 

If my model extends Baum/Node  the translations are not saved at all.

```
<?php

use Dimsav\Translatable\Translatable;

class Category extends Baum\Node
{
    use Translatable;

    protected $guarded = array('id', 'url');

    public $translatedAttributes = ['name', 'url'];
    public $translationModel = 'CategoryTranslation';

}
```

When changing `Baum/Node` to `Eloquent` the translations are saved correctly. 

How can this problem be solved?

**Comment by etrepat** [comment]
Sorry for jumping in so late on this.

There's no bug/issue in Baum. It just happens to hook on save events and perform several actions for keeping the table structure (housekeeping). 

Maybe we can find a way to make the packages compatible... @dimsav could you please give me some insight on why Baum is interfering with your save hooks?

**Comment by Fed03** [comment]
@etrepat basically this package saves the translations after the parent model is saved.
after it calls [this method](https://github.com/dimsav/laravel-translatable/blob/master/src/Translatable/Translatable.php#L255-L267) that loops over the `$this->translations` relationship.

but that property is empty because when your package save the parent model, the package relods the model from db and, obviously, the translations are not yet in db so that property doesn't exists

**Comment by etrepat** [comment]
Thanks @Fed03. 

So, if I understand correctly (please, correct me if I'm wrong)... 

It happens that when saving a `Baum\Node` instance, that node gets reloaded (this happens in two situations: the first being when that node is moved, and the second, when recomputing the node's depth) *before* the `Translatable::save()` extended method can perform its work. I understand that this is because Eloquent dispatches the `saved` event (which Baum hooks into) before returning from its `save` method, so `Translatable` just happens to go afterwards in the inheritance chain. The problem arises then, because the `saveTranslations()` method cannot find any "dirty" translations (because that instance has been freshened from the db) and so, the changes on them do not get saved (there's no change on them anyway at this point).

As I see it, it is indeed not a bug on neither side but just an incompatible way of dealing with model saving.

I can't come up with any obvious solution to this right now, because I have not looked into this package implementation very much, but maybe I can think of something to make the packages compatible.

**Comment by Antonimo** [comment]
Same problem with another nested set package, and I think its a general problem:
https://github.com/lazychaser/laravel-nestedset/blob/master/src/Node.php#L117
the 'saving' event is not fired, in Laravel model the saving event is always called:
```
public function save(array $options = array())
	{
		$query = $this->newQueryWithoutScopes();
		// If the "saving" event returns false we'll bail out of the save and return
		// false, indicating that the save failed. This provides a chance for any
		// listeners to cancel save operations if validations fail or whatever.
		if ($this->fireModelEvent('saving') === false)
		{
			return false;
		}
```
after that the 'saved' event is called.  
in translatable, the 'saved' event is sometimes not called;

**Comment by studiomado** [comment]
I had the same problem with Baum and I resolved with the solution of @freekmurze https://github.com/dimsav/laravel-translatable/issues/25#issuecomment-47740434

@dimsav can you add @freekmurze solution in master branch?

**Comment by acacha** [comment]
@etrepat @dimsav Any news on this issue? Could we find a way to make compatible the projects?

**Comment by k-zakhariy** [comment]
@dimsav I agree with @studiomado , can you add @freekmurze solution in master branch ?

**Comment by michaelstivala** [comment]
The solution provided by @freekmurze solved most of my issues - though I encountered a strange bug when running my integration tests when saving my translatable model.

When saving, the SQL query being generated was trying to save a column "translations", instead of saving it as a relation. I haven't looked into it very deeply, but Eloquent was mistaking the 'translations' relationship as an attribute. 

This is my workaround, a slight variation on @freekmurze (note the `$this->setRelation`):

```
<?php 

trait Translatable
{
    use \Dimsav\Translatable\Translatable;

    public function save(array $options = array())
    {
        $tempTranslations = $this->translations;
        if ($this->exists)
        {
            if (count($this->getDirty()) > 0)
            {
                // If $this->exists and dirty, parent::save() has to return true. If not,
                // an error has occurred. Therefore we shouldn't save the translations.
                if (parent::save($options))
                {
                    $this->setRelation('translations', $tempTranslations);
                    return $this->saveTranslations();
                }
                return false;
            }
            else
            {
                // If $this->exists and not dirty, parent::save() skips saving and returns
                // false. So we have to save the translations
                $this->setRelation('translations', $tempTranslations);
                return $this->saveTranslations();
            }
        }
        elseif (parent::save($options))
        {
            // We save the translations only if the instance is saved in the database.
            $this->setRelation('translations', $tempTranslations);
            return $this->saveTranslations();
        }
        return false;
    }
}
```

**Comment by datune** [comment]
@michaelstivala Works like a charm, thanks for sharing!

**Comment by zeraist** [comment]
@michaelstivala had the same error. Your solution worked. Thanks

**Comment by khairilanuar** [comment]
@michaelstivala thanks for your solution! still working until today!

**Comment by michaelstivala** [comment]
Glad that my solution has helped! I'm still using it too :)

**Comment by gunharth** [comment]
@michaelstivala 
Thank you! Working great here as well ...

**Comment by k-zakhariy** [comment]
When i saving these categories i am getting a lot of queries, can it be quite optimized ? Or it is normal behavior ?
```php
$c1 = Category::create([
            'ru' => [
                'title' => 'Root category'
            ]
        ]);
        $c2 = Category::create([
            'ru' => [
                'title' => 'Test1'
            ]
        ]);
        $c3 = Category::create([
            'ru' => [
                'title' => 'Root2 category'
            ]
        ]);
        $c4 = Category::create([
            'ru' => [
                'title' => 'Subcat'
            ]
        ]);
        $c5 = Category::create([
            'ru' => [
                'title' => 'Subcat2'
            ]
        ]);
        $c6 = Category::create([
            'ru' => [
                'title' => 'SubSubcat'
            ]
        ]);
        $c4->makeChildOf($c3);
        $c5->makeChildOf($c3);

        $c6->makeChildOf($c5);

        $c2->makeChildOf($c1);
```

![image](https://cloud.githubusercontent.com/assets/5267851/20790143/c944bfd2-b7bf-11e6-9c2d-a0172f0f1012.png)

**Comment by dimsav** [comment]
Feel free to make a pr if you see something that can be improved.

**Comment by k-zakhariy** [comment]
FYI , i used this package https://github.com/lazychaser/laravel-nestedset and it works great, more stable than Baum, and there is good feature to rebuilding a tree from array
