### ISSUE TITLE
Multiple models for translations

### ISSUE THREAD

**Issue by Cannonb4ll** [dimsav/laravel-translatable#313]
My main question really is, why did you choose for multiple models to get the translations done?

In my opinion it really clutters my application with extra models. Wouldn't a polymorphic model be better so you have 1 table with all translations, where you save the model_id and model_type?

So instead of 'PageTranslation' you have a main model 'Translation' (translations in db) where you have all your default fields such as title, description and such, where you define a polymorphic relation in.

**Comment by catalinux** [comment]
How about models that have different fields? Where would sit translation for their specific fields?

**Comment by Cannonb4ll** [comment]
I don't think its a bad idea to just add them to the main translation model, as some models would use the fields, and others would not.

**Comment by dimsav** [comment]
@Cannonb4ll thank you for your feedback.

Using this package we need to create a translation model and table because we take benefit of eloquent's one to many relationship to link the model and it's translations.

Of course this solution is not perfect and doesn't fit to all cases. This structure however is what makes this solution unique and therefore changing it would require rewriting from scratch.
