### ISSUE TITLE
[bug][7.0] translate does not respect Model's $useTranslationFallback property

### ISSUE THREAD

**Issue by Cyrille37** [dimsav/laravel-translatable#349]
Hi,
Thanks for your nice and usefully work.

Using dimsav/laravel-translatable v7.0

The `translate()` method does not care for model's $useTranslationFallback property.
To make it works, the `translate()` method signature hae to be changed as : 
```
public function translate($locale = null, $withFallback = null)
```

**Comment by Cyrille37** [comment]
I created the PR #350

**Comment by Cyrille37** [comment]
Not a bug. Read the doc again !

**Comment by marvinschroeder** [comment]
@Cyrille37 
I am in the state of using fallback per model. Why is this not a bug? When I changed the parameter to null instead of false everything works like expected. So I think it is a actually a bug.
To wrap it up:
I want to use fallback locales per model. I use $country->translate()->name where $useTranslationFallback = true; and $this->defaultLocale = 'de'; is defined on the model. Without changing the parameter it always show null if there is no current App::getLocale(); translation. When I change the parameter like in the PR #350 everything works like expected. I get a mix of existing translations matching App::getLocale(); ('en') and fallback translation with the defined $this->defaultLocale;
