### ISSUE TITLE
Does Model::insert work with translations?

### ISSUE THREAD

**Issue by Grundmanis** [dimsav/laravel-translatable#415]
I have such request:
```
"category_id" => array:1 [▼
    0 => "2"
  ]
  "en" => array:2 [▼
    "name" => "Test name"
    "value" => "default value"
  ]
  "type" => "text"
```

And here I want to save multiple filters with translations:
```
       $filters = [];
        foreach ($request->input('category_id') as $key => $id)
        {
            $filters[$key] = $request->except('_method','_token');
            $filters[$key]['category_id'] = $id;

        }
        Filter::insert($filters);
```
But in result I have the sql error:
```
Column not found: 1054 Unknown column 'en' in 'field list' (SQL: insert into `filters` (`category_id`, `en`, `type`) values (2, Test name, text))
```
It works, if I use `->create($filter)` method

**Comment by Gummibeer** [comment]
This will never work cause `Model::insert()` goes directly into the builder and not the eloquent save logic.

What happens if you call `Model::insert()`!?
1) `\Illuminate\Database\Eloquent\Model::__callStatic`
2) `\Illuminate\Database\Eloquent\Model::__call`
3) `\Illuminate\Database\Eloquent\Builder::__call`
4) `\Illuminate\Database\Query\Builder::insert`

It never get's into the model logic. So if you want to create multiple at once you have to use the model methods not any passthrough ones. In your case `Model::create`.
