### ISSUE TITLE
How do i use with laravel-admin?

### ISSUE THREAD

**Issue by arwtyxouymz** [dimsav/laravel-translatable#476]
HI

I'm developing CMS with [laravel-admin](https://github.com/z-song/laravel-admin) and I want to use this plugin with `laravel-admin`.

**What i want to do is to get the data with specifying the locale and to save the data with specifying the locale.**

So I tried quick access like`{'title:en'}` but it didn't work
```php
$form->text('title:en');
```

Then i tried
```php
$form->text('title');
```
this worked only with current locale.

I know i should change Model file of `laravel-admin`, but i don't know how fix it.
I'm not cling to `{'title:en'}`.
I just want to get data specified the locale and save data specified locale.
please help me!

**Comment by Gummibeer** [comment]
The problem is that these pseudo-attributes are 100% dynamic generated. And the Form class of the mentioned admin package uses some strange self-data-collecting. I haven't tested it but I think that [laravelcollective/html](https://laravelcollective.com/docs/master/html) works with this package to generate forms.
