### ISSUE TITLE
translateOrNew

### ISSUE THREAD

**Issue by bibiseb** [dimsav/laravel-translatable#490]
Hello,

I'am trying to create a translation for a given country. You can check the code below. With that code I get this error: _General error: 1364 Field 'country_id' doesn't have a default value (SQL: insert into `country_translations` (`locale`, `name`) values (fr, Belgique))_

```php
<?php

$country = Country::findOrFail(24);
$translation = $country->translateOrNew('fr');
$translation->name = 'Belgique';
$translation->save();
```
Can you say me the right way to do that ?

**Comment by Gummibeer** [comment]
Atm I'm on the road but so far I got the method just adds the new translation to the translation relation collection on the main model.
```php
 $this->translations->add($translation);
```

Can you try to call `save()` on the main model? This should solve this. If even this doesn't solve this it's a real bug. Otherwise I would also fix it but not as important.^^
To fix it a simple second setAttribute call in getNewTranslation for the foreign key should be enough.

But instead of `save()` calls I would go for `assosiciate()`.

**Comment by Gummibeer** [comment]
And why it's in all cases a bug:

```php
$country->translateOrNew('de')->fill(...)->save();
```

Should be possible - otherwise this method is nearly useless!

**Comment by dimsav** [comment]
As announced [here](https://twitter.com/dimsav/status/1140750099875860481), the project has been deprecated. Please use [astrotomic/laravel-translatable](https://github.com/Astrotomic/laravel-translatable).
