### ISSUE TITLE
Undefind index error

### ISSUE THREAD

**Issue by markvdputten** [dimsav/laravel-translatable#528]
Hi,

After upgrading the package to version 9.2 I am receiving the following error on my translation model:
Undefined index: App\Models\PageTranslation

The stack trace points to:

/**
     * Initialize any initializable traits on the model.
     *
     * @return void
     */
    protected function initializeTraits()
    {
        foreach (static::$traitInitializers[static::class] as $method) {
            $this->{$method}();
        }
    }

Has anyone else bumped into this? This package has been working wonders so far for me, but this one has gotten my quite stumped. Thanks in advance for any help.

**Comment by Gummibeer** [comment]
Hey, never got this and this method is part of laravel core.
I've no idea in which way this package should/could produce this exception. 🤔

**Comment by Gummibeer** [comment]
Don't know if it would fix it but so far I know you have to call `parent::boot()` if you override this method. Otherwise it won't boot all the core things for the model and can't flag it as booted.

My own recommendation: use observer classes to do this. The listeners are stored at one clean place, won't bloat the model itself and you don't have to override core methods - something I try to prevent as long as possible.
And for your case it could be a solution to use a trait `Slugable` and use the trait boot method.
https://laravel-news.com/booting-eloquent-model-traits

If all this boot related thing won't help I will have to take a closer look.

**Comment by markvdputten** [comment]
Oh my ... you are so right... I am surprised this used to work before the upgrade a couple of days ago... I am so sorry for taking your time with this non issue. Really do appreciate your help and thinking with me on this one... thanks a million!
