### ISSUE TITLE
Disable translation for initial creation? 

### ISSUE THREAD

**Issue by sheriffmarley** [dimsav/laravel-translatable#530]
We need to extend a website for multilingual use. 
We have created a second table for it `article_translation` and the original table `articles`.
So far it works as expected, but we have an huge issue to store the original content in the `articles` tables. The translatable attributes for the original article are always stored in the translation table.

So how can we store the data in the original table instead of the translation table? 
Currently all new entries are stored in the translations table, but we need the original translation in the original table.

The table is filled through the `create` method.

**Comment by sheriffmarley** [comment]
Nevermind. Removed the "default locale" from the locales array and it works now as expected.

**Comment by Gummibeer** [comment]
From an outside perspective: this is strange wanted behavior.
This package is meant to store translated values. There is no locale `original` so in which locale is the original value? This should be saved in the translation table. Otherwise you will also have to adjust the getter logic.

If this works it's ok, for me as package maintainer you described a bug because this case should throw an invalid locale exception.
