### ISSUE TITLE
Translatable save method has a problem

### ISSUE THREAD

**Issue by weiwenhao** [dimsav/laravel-translatable#538]
![image](https://user-images.githubusercontent.com/24819514/49365084-d3d89200-f720-11e8-9aa9-90e199f1eb1d.png)
Above is the translatable save method

![image](https://user-images.githubusercontent.com/24819514/49365202-24e88600-f721-11e8-9f5e-ee009f9da6fc.png)
Above is laravel default save method

When I modify the attribute in the saving observer, isDirty is not called, causing the model to not be updated.

**Comment by Gummibeer** [comment]
Multiple things that come to my mind related to this:
1. You are 100% right we shouldn't change the core behavior if this isn't the job of this package!
2. For me it's a core bug - calling `save()` without changes just to update it in a listener sounds wrong for me. But I bet that this was changed sometimes because anyone had a good usecase I just can't imagine.
3. We shouldn't override the `save` method at all but use one of the events - for me it should be the after `saved` event. But this would prevent save translations without a dirty model. So I will try to find a good solution to don't override all the core logic but save translations everytime needed.

**Comment by schelmo** [comment]
perhaps do it like in https://github.com/vinkla/laravel-translator/pull/82
and use the created & updating events

**Comment by Gummibeer** [comment]
Okay, I've checked it and the idea with the events would work if we wouldn't save translations if the main model isn't dirty.
The current implementation also fires the events in the right order.

https://github.com/dimsav/laravel-translatable/blob/f1d5569b6c89da1e89dbe48b9bcbb9e54b0afa2c/src/Translatable/Translatable.php#L253-L276

**Comment by schelmo** [comment]
Right.
Another Idea would be to use the saved event then. or is it too late?
finishSave is called (and saved event is dispatched) if $saved == true
if the model isnt dirty $saved will be still true:
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Eloquent/Model.php#L655

**Comment by Gummibeer** [comment]
@schelmo this would be the only event and it would work. We would only change the behavior if the model exist but isn't dirty.
AT the moment we won't fire `saved` and `updated` if the `saveTranslations()` isn't successful - even if the order of the two events isn't right ... 🙈 

I will do it and let @dimsav decide if this is a real BC or if we cover it under bug-fixing - I favor the latter one.

**Comment by Gummibeer** [comment]
@schelmo could you check/review https://github.com/dimsav/laravel-translatable/pull/567 ? If it's what you want?^^

**Comment by Gummibeer** [comment]
https://github.com/dimsav/laravel-translatable/releases/tag/v10.0.0
