### ISSUE TITLE
Fetching Model by translated field and determine locale

### ISSUE THREAD

**Issue by BurakKartal1** [dimsav/laravel-translatable#561]
Im trying to get post by their slug value which is translated field.

Example: 
sitename.com/something-french

i have looked up on documentation but there was no method that can help in this situation. I know there is a whereTranslation but that returns only Post model not translation. Also slug determines which locale to show thats why query that was presented

````
    $article = Article::select('articles.id', 'article_translations.slug')
        ->join('article_translations', 'articles.id', '=', 'article_translations.article_id')
        ->where('slug', $slug)
        ->firstOrFail();
````

#44 in this issue is not helpfull. When i dump the returned value it actually shows the right values but when accessing those values they are returned to App:Locale value which is english.

right now, i solved it by doing this >
`\App::setLocale($post->getAttributes()['locale']);`

it would be more convenient if there was a built-in method.

**Comment by Gummibeer** [comment]
Hey @BurakKartal1 ,
you are right - out of the box there is no scope that does all of it. We have several scope that do single parts of it - but I don't know if they work right combined.
* `setDefaultLocale()` set the default locale 
* `scopeWithTranslation()` load only the translation for the set locale
* `scopeWhereTranslation()` query the original model by a translated value

Because it needs at least 2 queries in all scenarios it could be that you have to write your own wrapper method to do this.

Am I right that you also need all other translations in the given locale for this request? If so I would do it the following way:
```php
class ArticleController {
  public function show(ArticleTranslations $translation) {
    \App::setLocale($translation->locale);
    $article = $translation->article; // reverse relation method of $article->translations
    // do your other stuff
  }
}
```

To let this work you have to define the `ArticleTranslation::getRouteKeyName()` to `slug` https://laravel.com/docs/5.8/routing#route-model-binding
This would use the most of eloquent/laravel core logic and you don't have to care too much about model resolving.

**Comment by BurakKartal1** [comment]
This works perfectly. Thanks !

**Comment by Gummibeer** [comment]
@BurakKartal1 happy to help! 😊
