### ISSUE TITLE
Display translated attribute even if no translation for current locale and fallback locale?

### ISSUE THREAD

**Issue by derekphilipau** [dimsav/laravel-translatable#564]
The following issue occurs in systems with locales > 2.

Imagine a Recipe database using laravel-translatable.  Fallback locale is "en".

Users enter recipes in many different languages:
- German user creates new recipe with $recipe->name = "Mein Rezept"
- French user creates new recipe with $recipe->name = "Ma recette"
- English user creates new recipe with $recipe->name = "My recipe"

These recipe names appear in the recipe_translations table under the _de_, _fr_ and _en_ locales.

French user with "fr" locale now searches for all recipes, returning 3 results:
- $recipe->name property is displayed for the French recipe as "Ma recette"
- $recipe->name property is displayed for the English recipe as "My recipe" (fallback locale "en")
- $recipe->name property is **not** displayed for the German recipe (no translation for user locale of "fr" and no translation for fallback locale of "en")

**Question:**  What is the best way to ensure that a translated property ($recipe->name) is _always_ displayed, even if there is no translation for the current user locale and the fallback locale?

In the above example, rather than _nothing_ being displayed for the German recipe, ideally the german translation is displayed.

Is there some way to implement:
1. If there is a translation in the current locale (fr), return it!
2. If there is a translation in the fallback locale (en), return it!
3. If there is any translation, just return the first one (de).
4. Return null

But it might be better if each model row had it's own fallback translation locale:
1. If there is a translation in the current locale (fr), return it!
2. If there is a translation in the fallback locale (en), return it!
3. If there is a translation in the model instance fallback locale (de), return it!
4. Return null

EDIT:

duplicate #224
In regards to #244:
It is often the case that we wish to search for ALL items in a database regardless of locale. And the translated properties of these items should be displayable, even if they are not in the current user's locale and not the fallback locale. The idea in #244 to add a custom property to the model such as "primary_locale" would work, as would adding a "isPrimary" boolean value to the translations table. I think this is very important in systems with more than just two languages.

For now I'm following similar advice as is offered in #224, adding a "default_locale" attribute to my model:
```
<?php

namespace App\Models;

use Dimsav\Translatable\Translatable;

trait DefaultableTranslatable
{
    use Translatable;

    private function getFallbackLocale($locale = null)
    {
        if ($locale && $this->isLocaleCountryBased($locale)) {
            if ($fallback = $this->getLanguageFromCountryBasedLocale($locale)) {
                return $fallback;
            }
        }

        if (isset($this->default_locale)) {
            return $this->default_locale;
        }

        return config('translatable.fallback_locale');
    }
}
```

**Comment by derekphilipau** [comment]
duplicate #224

**Comment by derekphilipau** [comment]
In regards to #244:

It is often the case that we wish to search for ALL items in a database regardless of locale.  And the translated properties of these items should be displayable, _even if they are not in the current user's locale and not the fallback locale_.  The idea in #244 to add a custom property to the model such as "primary_locale" would work, as would adding a "isPrimary" boolean value to the translations table.  I think this is very important in systems with more than just two languages.

**Comment by Gummibeer** [comment]
Hey,
first of all thanks for this complete issue! :) 
Just to link another issue #534 had a similar/same problem with again the same solution.
Because all these ideas get to the same result and are made by different people in different states of this package I would say that there isn't another/better way. So saving the locale the model was original created in on the main model and use this a fallback seems a good idea.

Because of this complete issue and some insights in your usecase I want to add some brain-farts to it:
* As a user I wouldn't want all recipes if they are written in languages I don't understand. So lets' say I have a profile where I say that I need the app in german and if the translation isn't available I want english. It could be that I speak more languages so you could make the fallback dropdown a multi-select or add a multi-select to the recipe search/index page where I can say that I also want french recipes.
* The moment we get to search we talk, most times, about full-text search which is language dependent - so if I write my search in german I also only need hits in german. My search query could mean something different in another language - so even if the words match it doesn't mean that this is what I want.
* For search and primary fulltext search over multiple translated attributes (name, description, ingredients, preparation and so on I would never recommend doing this via MySQL but ElasticSearch or any search optimized DB. There you can setup an index for every language. The german index contains only recipes written in german and so on. 
* Adding the default language could also increase UX if you add a note that this is the original text or that it's translated and could contain translation errors. Like a translated twitter post where I also cans witch to the original one.

**Comment by derekphilipau** [comment]
Thanks for your thoughts, they help me better understand my own issue.  Although perhaps not common, there are definitely situations in which we want to be able to search across multiple languages.  But some complications arise in this case.

Even with the complications, laravel-translatable is working very well for me now.

As you say, this problem keeps coming up, maybe a note should be added in the docs.  But I realize now it's really more of a software design problem and not a problem with the package, so this issue should probably be closed.

**Comment by derekphilipau** [comment]
Consider adding a note to the docs regarding search in systems with greater than two locales.
