### ISSUE TITLE
ID coming back with different data

### ISSUE THREAD

**Issue by ScottyRobinson** [dimsav/laravel-translatable#568]
Hello

We're running into a bit of problem at the moment; When we post an article, sometimes an article from a year ago is shown instead.

I'm not overly sure how to counter this. From what I understand, the problem is in the translations table.

```
posts - table
id, updated_at, created_at,
3949, null, null
32589, null, null
```

```
post_translations - table
id, post_id, etc
6, 3949,
3949, 32589
```

When trying to show the post with id, 32589, it's coming back with post_translations.id 6 information instead.

Any ideas?

```php
$posts = Post::join('post_translations as t', function ($join) {
            $join->on('t.post_id', '=', 'posts.id')
              ->where('t.locale', '=', \App::getLocale());
          })
          ->where('t.user_id', '=', Auth::User()->id)
          ->orderBy('t.scheduled_at', 'desc')
          ->paginate( 25 );
```

**Comment by Gummibeer** [comment]
I haven't tested it but could you try to run the query in a real sql client? (sequel pro, mysql workbench, phpstorm or any)

```mysql
SELECT *
FROM posts
JOIN post_translations as t ON t.post_id = posts.id AND t.locale = ?
WHERE t.user_id = ?
```

Because of the same column name `id` in `posts` and `post_translations` I believe that mysql gets conflicts. This is a very common problem.
https://stackoverflow.com/questions/5090513/how-do-you-avoid-column-name-conflicts

Have you checked the already existing `withTranslation()` scope?
https://github.com/dimsav/laravel-translatable/blob/f1d5569b6c89da1e89dbe48b9bcbb9e54b0afa2c/src/Translatable/Translatable.php#L605-L620

**Comment by ScottyRobinson** [comment]
Having changed the post_translations.id to post_t_id, when trying to save it no longer works as every save() query on the model is looking for the id column.

**Comment by Gummibeer** [comment]
Have you changed the `protected $primaryKey` property?

**Comment by ScottyRobinson** [comment]
Duh! Of course. Completely slipped my mind. I appreciate the support, thank you for the help.
