### ISSUE TITLE
What would be the best way to handle admin panel with translations?

### ISSUE THREAD

**Issue by zefexdeveloper** [dimsav/laravel-translatable#570]
I plan on creating an admin panel and for that I have a resource route for `categories`, what would be the best way to handle translations for a certain field such as `name` (for creating and editing for example)?

**Comment by Gummibeer** [comment]
What do you mean? This package isn't about frontend. It's up to you to decide how you want to handle translations.
There are several ways to save translations. Choose the one that best fits your needs.

**Comment by zefexdeveloper** [comment]
@Gummibeer Hi, sorry for the vague question. I know that it's not about frontend and there might be several ways to do that, the real thing is that I know none and I was wondering if you could say a way to handle that so I can implement in my application, can't think of any.
Thank you @Gummibeer for your answer and time

**Comment by Gummibeer** [comment]
The first idea I get is to use the ability to save multiple locales at ones.

```php
$data = [
    'code' => 'gr',
    'en'  => ['name' => 'Greece'],
    'fr'  => ['name' => 'Grèce'],
  ];

  $greece = Country::create($data);
```
This is from the docs. In HTML your input names would be `code`, `de[name]` and `fr[name]`.

With this HTML you could just take `$request->all()` and fill it in your model.

This way would also work great with APIs (Vue frontend) because the locales are keys which contain an array with the translated attributes.

The other way is to use names like `name:en` and `name:fr` which won't result in any cool data structure but only adjusted keys.

For the userflow you have tons of ways and this package should be able to handle all of them.
You can create a big form with all locales in a single form (not recommended for a lot locales).
You can also have a single form per locale (not recommended for translators who want to translate a lot of shit).
You could also have the name input in the main form with a button which opens a modal window to translate this field in all locales. The default input could be everytime your main language or the current user language.

I hope that this will help you!?

**Comment by zefexdeveloper** [comment]
@Gummibeer Thank you very much for the answer. I think I will go with the `de[name]` example. I also found in the docs this package https://github.com/TypiCMS/TranslatableBootForms that might help me with this. I will only have three languages: english, spanish and portuguese so I don't think it's too much to put three input fields for them.
Have an awesome day and thanks again for everything.
