### ISSUE TITLE
Multiple Databases

### ISSUE THREAD

**Issue by wyred** [dimsav/laravel-translatable#572]
I'm building a side project that accesses some data in the database of my main project.

Both projects use this package.

So when I want to pull data from my main project, I use a model that has its $connection property specified to connect to the main project database.

    class Car extends Model
    {
        use Translatable;
    
        protected $connection = 'main_db';
    
        public $translatedAttributes = [
            'name',
        ];
    }

Since this model has translations in the main project database, I created the CarTranslation model:

    class CarTranslation extends Model
    {
        protected $connection = 'main_db';
    
        protected $fillable = [
            'name',
        ];
    }

I'm able to fetch data for the Car model, but when I try to get the translations, all I get is null.

Since it works fine in my main project, I suppose connecting to a non-default database is not supported for now?

**Comment by Gummibeer** [comment]
Because we don't use custom queries anywhere and we even had/have an unittest which has splitter the main model and translations in two databases I would say that it would/should work.
Could you try to test if your setup is able to retrieve translations with a direct query on the model instead of loading it as relationship?
```php
CarTranslation::limit(5)->get();
```
If this works the problem is in the relationship/our package. If it also doesn't work the problem is in the model/connection/eloquent itself.

And could you use a package like debugbar or telescope to list all executed queries and check if something looks wrong?

And last question: which method do you use? The translations relation method or the attribute getter or do you try to use one of the scopes?

**Comment by wyred** [comment]
The problem was because I had used a different `locale_key` in my main project and forgot to set it in the side project. After creating the config file and setting the correct locale_key, it works fine.

Sorry for the trouble!
